/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import java.sql.ResultSet;
import  controle.dadosPessoaisC;
import  java.util.ArrayList;
import modelo.dadosPessoaisM;
import javax.swing.JOptionPane;
import java.util.List;
import controle.dadosPessoaisC;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arthur
 */
public class dadospessoaisV extends javax.swing.JFrame {
    dadosPessoaisC control=new dadosPessoaisC(); 

    /**
     * Creates new form dadospessoaisV
     */
    public dadospessoaisV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consulta = new java.awt.Button();
        cadastro = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jcoddp = new javax.swing.JLabel();
        jTextcoddp = new javax.swing.JTextField();
        jnome = new javax.swing.JLabel();
        jTextnome = new javax.swing.JTextField();
        jidade = new javax.swing.JLabel();
        jTextidade = new javax.swing.JTextField();
        jrg = new javax.swing.JLabel();
        jTextrg = new javax.swing.JTextField();
        jcpf = new javax.swing.JLabel();
        jTextcpf = new javax.swing.JTextField();
        jsexo = new javax.swing.JLabel();
        jTextsexo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabelaConsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consulta.setActionCommand("consulta");
        consulta.setLabel("cadastro");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
                cadastro(evt);
            }
        });

        cadastro.setLabel("consulta");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDadospessoias(evt);
            }
        });

        jcoddp.setText("CODDP:");

        jTextcoddp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextcoddpMouseClicked(evt);
            }
        });
        jTextcoddp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcoddpActionPerformed(evt);
            }
        });

        jnome.setText("NOME:");

        jidade.setText("IDADE:");

        jrg.setText("RG:");

        jTextrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextrgActionPerformed(evt);
            }
        });

        jcpf.setText("CPF:");

        jTextcpf.setText(" ");

        jsexo.setText("SEXO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextnome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcoddp)
                        .addGap(18, 18, 18)
                        .addComponent(jTextcoddp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextrg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextidade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcoddp)
                    .addComponent(jTextcoddp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnome)
                    .addComponent(jTextnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jidade)
                    .addComponent(jTextidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrg)
                    .addComponent(jTextrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcpf)
                    .addComponent(jTextcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsexo)
                    .addComponent(jTextsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "coddp", "nome", "idade", "rg", "cpf", "sexo"
            }
        ));
        jScrollPane3.setViewportView(jTabelaConsulta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel1.setText("DADOS PESSOAIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaActionPerformed

    private void jTextcoddpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcoddpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcoddpActionPerformed

    private void jTextcoddpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextcoddpMouseClicked
                


    }//GEN-LAST:event_jTextcoddpMouseClicked

    private void jTextrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextrgActionPerformed

    private void cadastro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro
try {
    // Coletando os dados da interface gráfica
    String coddpStr = jTextcoddp.getText();
    String nome = jTextnome.getText();
    String idadeStr = jTextidade.getText();
    String cpf = jTextcpf.getText();
    String rg = jTextrg.getText();
    String sexo = jTextsexo.getText();

    // Validação simples dos campos
    if (coddpStr.isEmpty() || nome.isEmpty() || idadeStr.isEmpty() || cpf.isEmpty() || rg.isEmpty() || sexo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
        return;
    }

    int idade;
    int coddp;

    // Validação dos campos numéricos
    try {
        coddp = Integer.parseInt(coddpStr);
        idade = Integer.parseInt(idadeStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Cód. DP e Idade devem ser números válidos!");
        return;
    }

    // Validação adicional para o campo "sexo"
    if (sexo.length() != 1 || (!sexo.equalsIgnoreCase("M") && !sexo.equalsIgnoreCase("F"))) {
        JOptionPane.showMessageDialog(null, "Sexo deve ser 'M' ou 'F'!");
        return;
    }

    // Cria um objeto do tipo dadosPessoaisM
    dadosPessoaisM dadosPessoais = new dadosPessoaisM(coddp, nome, idade, rg, cpf, sexo.charAt(0));

    // Chamando o método de cadastro no controlador
    String resposta = control.CadastroDadospessoais(dadosPessoais);

    // Exibe o resultado do cadastro
    if ("OK".equals(resposta)) {
        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

        // Limpa os campos após o cadastro
        jTextcoddp.setText("");
        jTextnome.setText("");
        jTextidade.setText("");
        jTextcpf.setText("");
        jTextrg.setText("");
        jTextsexo.setText("");
    } else {
        JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + resposta);
    }
} catch (Exception erro) {
    erro.printStackTrace();
    JOptionPane.showMessageDialog(null, "Erro inesperado: " + erro.getMessage());
}

    }//GEN-LAST:event_cadastro

    private void consultaDadospessoias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDadospessoias
try {
        // Obtenha o modelo da tabela
        DefaultTableModel tabelaModelo = (DefaultTableModel) jTabelaConsulta.getModel();

        // Limpa os dados existentes na tabela
        tabelaModelo.setRowCount(0);

        // Coleta o filtro de nome da interface gráfica (opcional)
        String nome = jTextnome.getText();

        // Consulta no banco de dados
        List<dadosPessoaisM> resultados = control.ConsultaDadospessoais(nome); // Ajuste o método conforme seu controlador

        // Preenche a tabela com os resultados
        for (dadosPessoaisM dados : resultados) {
            Object[] linha = {
                dados.getCoddp(),
                dados.getNome(),
                dados.getIdade(),
                dados.getCpf(),
                dados.getRg(),
                String.valueOf(dados.getSexo())
            };
            tabelaModelo.addRow(linha);
        }

        // Caso não existam resultados
        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!");
        }
    } catch (Exception erro) {
        erro.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao consultar dados: " + erro.getMessage());
    }
    }//GEN-LAST:event_consultaDadospessoias

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dadospessoaisV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dadospessoaisV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dadospessoaisV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dadospessoaisV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dadospessoaisV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cadastro;
    private java.awt.Button consulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabelaConsulta;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextcoddp;
    private javax.swing.JTextField jTextcpf;
    private javax.swing.JTextField jTextidade;
    private javax.swing.JTextField jTextnome;
    private javax.swing.JTextField jTextrg;
    private javax.swing.JTextField jTextsexo;
    private javax.swing.JLabel jcoddp;
    private javax.swing.JLabel jcpf;
    private javax.swing.JLabel jidade;
    private javax.swing.JLabel jnome;
    private javax.swing.JLabel jrg;
    private javax.swing.JLabel jsexo;
    // End of variables declaration//GEN-END:variables
}
